apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product1-be
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/emzm17/Product1
    targetRevision: main
    path: product1/product1-be-config/manifests-be

  destination:
    server: https://kubernetes.default.svc
    namespace: product1-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true

      