apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product1-root
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/emzm17/Product1
      targetRevision: main
      path: product1/product1-be-config/argo

    - repoURL: https://github.com/emzm17/Product1
      targetRevision: main
      path: product1/product1-fe-config/argo

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true